apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::011126499615:role/eksctl-eksctl-demo-nodegroup-ng-5-NodeInstanceRole-W8RT5QMZBA4
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::011126499615:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-27T12:08:32Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1384"
  uid: e8c3bd26-371f-432c-bebf-47744ac34672
